package com.miguelcr.contextmenu.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.miguelcr.contextmenu.entities.Fruit;

import com.miguelcr.contextmenu.entities.FruitDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fruitDaoConfig;

    private final FruitDao fruitDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fruitDaoConfig = daoConfigMap.get(FruitDao.class).clone();
        fruitDaoConfig.initIdentityScope(type);

        fruitDao = new FruitDao(fruitDaoConfig, this);

        registerDao(Fruit.class, fruitDao);
    }
    
    public void clear() {
        fruitDaoConfig.getIdentityScope().clear();
    }

    public FruitDao getFruitDao() {
        return fruitDao;
    }

}
